---
include:
  - board: nice_nano_v2
    shield: comfykey_left
  - board: nice_nano_v2
    shield: comfykey_right
  - board: nice_nano_v2
    shield: comfykey_dongle dongle_display
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
