---
include:
  - board: nice_nano
    shield: comfykey_left
  - board: nice_nano
    shield: comfykey_right
  - board: nice_nano
    shield: comfykey_dongle 
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y